USE ROLE ACCOUNTADMIN;

USE WAREHOUSE BIG_DATA_PROJECT;

CREATE DATABASE IF NOT EXISTS BOOKSHOP;

USE DATABASE BOOKSHOP;

-- DROP DATABASE BOOKSHOP;


CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS WAREHOUSE;
CREATE SCHEMA IF NOT EXISTS MARTS;

CREATE TABLE IF NOT EXISTS RAW.CATEGORY (
  "CATEGORY_ID" integer PRIMARY KEY,
  "CATEGORY_INTITULE" varchar,
  "CREATED_AT" timestamp
);

CREATE TABLE IF NOT EXISTS RAW.BOOKS (
  "BOOKS_ID" integer PRIMARY KEY,
  "BOOKS_CATEGORY_ID" integer,
  "BOOKS_CODE" varchar,
  "BOOKS_INTITULE" varchar,
  "BOOKS_ISBN_10" varchar,
  "BOOKS_ISBN_13" varchar,
  "CREATED_AT" timestamp
);

CREATE TABLE IF NOT EXISTS RAW.CUSTOMERS (
  "CUSTOMERS_ID" integer PRIMARY KEY,
  "CUSTOMERS_CODE" varchar,
  "CUSTOMERS_FIRST_NAME" varchar,
  "CUSTOMERS_LAST_NAME" varchar,
  "CREATED_AT" timestamp
);

CREATE TABLE IF NOT EXISTS RAW.FACTURES (
  "FACTURES_ID" integer PRIMARY KEY,
  "FACTURES_CODE" varchar,
  "FACTURES_DATE_EDIT" varchar,
  "FACTURES_CUSTOMERS_ID" integer,
  "FACTURES_QTE_TOTALE" integer,
  "FACTURES_TOTAL_AMOUNT" float,
  "FACTURES_TOTAL_PAID" float,
  "CREATED_AT" timestamp
);

CREATE TABLE IF NOT EXISTS RAW.VENTES (
  "VENTES_ID" integer PRIMARY KEY,
  "VENTES_CODE" varchar,
  "VENTES_DATE_EDIT" varchar,
  "VENTES_FACTURES_ID" integer,
  "VENTES_BOOKS_ID" integer,
  "VENTES_PU" float,
  "VENTES_QTE" integer,
  "CREATED_AT" timestamp
);

USE BOOKSHOP.RAW;

ALTER TABLE "BOOKS" ADD FOREIGN KEY ("BOOKS_CATEGORY_ID") REFERENCES "CATEGORY" ("CATEGORY_ID");

ALTER TABLE "VENTES" ADD FOREIGN KEY ("VENTES_BOOKS_ID") REFERENCES "BOOKS" ("BOOKS_ID");

ALTER TABLE "VENTES" ADD FOREIGN KEY ("VENTES_FACTURES_ID") REFERENCES "FACTURES" ("FACTURES_ID");

ALTER TABLE "FACTURES" ADD FOREIGN KEY ("FACTURES_CUSTOMERS_ID") REFERENCES "CUSTOMERS" ("CUSTOMERS_ID");
